Enable adding documents
cpacker/MemGPT pull request #1864
Opened 2024-10-10 20:41 UTC by mattzh72

## Description

Enable adding documents. Specifically, this PR:

- Defines data models for `Document` objects
- Supports storing documents in SQL databases
- Adds an API route to retrieve all the documents associated with a source

Also, adds some items to the `.gitignore`. 

## Testing
Added a test that loads the `memgpt` paper, retrieves the documents via the new API route, and confirms that:

1. the correct number of documents were made
2. the metadata contains the right file name
3. the sources are set correctly on the documents

2024-10-10 21:00 UTC, sarahwooders requested changes
We may want to rename this concept to a file, and associate it with an entire PDF (or file more generally) that gets uploaded.

2024-10-10 22:07 UTC, mattzh72 commented on .gitignore
> +openapi_letta.json
We currently don't push this to the repo, so safe to add here.

2024-10-10 22:08 UTC, mattzh72 commented on letta/config.py
> +    # database configs: document storage
ack

2024-10-10 22:10 UTC, mattzh72 commented on letta/data_sources/connectors.py
>          document = Document(
Ah got it, was mirroring Passage below.

2024-10-10 23:16 UTC, mattzh72 commented on letta/server/rest_api/routers/v1/sources.py
> +@router.get("/{source_id}/documents", response_model=List[Document], operation_id="list_documents_from_source")
Will leave this to future PRs, doesn't seem needed by shub rn

2024-10-10 23:16 UTC, mattzh72 commented on letta/server/rest_api/routers/v1/sources.py
> +@router.get("/{source_id}/documents", response_model=List[Document], operation_id="list_documents_from_source")
planning to add delete API in future PR as well

2024-10-10 23:22 UTC, sarahwooders commented on letta/agent_store/storage.py
> +DOCUMENT_TABLE_NAME = "letta_documents"  # original files (from source)
delete?

2024-10-10 23:30 UTC, mattzh72 commented on letta/agent_store/storage.py
> +DOCUMENT_TABLE_NAME = "letta_documents"  # original files (from source)
renamed

2024-10-12 00:21 UTC, sarahwooders approved these changes

2024-10-12 00:21 UTC, sarahwooders commented on letta/schemas/file.py
> +    __id_prefix__ = "doc"
rename to `doc`?

2024-10-12 00:21 UTC, sarahwooders commented on examples/notebooks/data_connector.ipynb
> +    "from letta.schemas.document import File\n",
`FileMetadata`?

2024-10-12 00:32 UTC, mattzh72 commented on examples/notebooks/data_connector.ipynb
> +    "from letta.schemas.document import File\n",
ack

2024-10-12 00:32 UTC, mattzh72 commented on letta/schemas/file.py
> +    __id_prefix__ = "doc"
ack good catch

2024-10-12 00:33 UTC, mattzh72 commented on letta/data_sources/connectors.py
> +    document_store: StorageConnector,
ack

2024-10-12 00:34 UTC, mattzh72 commented on letta/client/client.py
> +    def list_files_from_source(self, source_id: str, limit: int = 10, cursor: Optional[str] = None) -> PaginatedListFilesResponse:
done

2024-10-12 00:35 UTC, mattzh72 commented on letta/data_sources/connectors.py
> +    def generate_passages(self, file_text: str, file: File, chunk_size: int = 1024) -> Iterator[Tuple[str, Dict]]:  # -> Iterator[Passage]:
discussed offline, reshaped interface, see updated code

2024-10-12 00:35 UTC, mattzh72 commented on letta/data_sources/connectors.py
> +    def generate_files(self) -> Iterator[Tuple[str, Dict]]:
sounds good - discussed offline, basically user should take in last given file and pass that in as a cursor

2024-10-12 00:35 UTC, mattzh72 commented on letta/client/client.py
> +    def list_files_from_source(self, source_id: str, limit: int = 10, cursor: Optional[str] = None) -> PaginatedListFilesResponse:
done

2024-10-12 00:35 UTC, mattzh72 commented on letta/client/client.py
> +        return PaginatedListFilesResponse(**response.json())
ack

2024-10-12 01:09 UTC, mattzh72 commented
cc @4shub for correctness - I noticed it didn't mention dropping the Documents table or adding a new FileMetadata table - is this expected?

2024-10-13 15:18 UTC, 4shub commented
This is correct, alembic only does any change on database deletions or modifications. You did not remove any database you just removed a scheme

2024-10-14 17:22 UTC, merged