fix typo in the base system prompt
cpacker/MemGPT pull request #189
Opened 2023-10-30 00:26 UTC by yubozhao

2023-10-30 03:58 UTC, cpacker requested changes

2023-10-30 03:58 UTC, cpacker commented on memgpt/prompts/system/memgpt_base.txt
> +Unlike a human, your brain is not continuously thinking, but is run in short burst.
can you change this to "bursts"?

2023-10-30 03:58 UTC, cpacker commented on memgpt/prompts/system/memgpt_base.txt
> +From now on, you are going to act as your persona.
can you remove this diff?

2023-10-30 17:17 UTC, yubozhao commented on memgpt/prompts/system/memgpt_base.txt
> +Unlike a human, your brain is not continuously thinking, but is run in short burst.
Yep

2023-10-30 17:17 UTC, yubozhao commented on memgpt/prompts/system/memgpt_base.txt
> +From now on, you are going to act as your persona.
Yep

2023-11-03 06:37 UTC, cpacker approved these changes
sorry for the delay! thanks for the PR

2023-11-03 06:37 UTC, merged