fix: LocalArchivalMemory prints ref_doc_info on if not using EmptyIndex
cpacker/MemGPT pull request #240
Opened 2023-11-01 12:59 UTC by goetzrobin

Currently, if you run the /memory command the application breaks if the LocalArchivalMemory has no existing archival storage and defaults to the EmptyIndex. This is caused by EmptyIndex not having a ref_doc_info implementation and throwing an Exception when that is used to print the memory information to the console. This hot fix simply makes sure that we do not try to use the function if using EmptyIndex and instead prints a message to the console indicating an EmptyIndex is used.

This is just a hot fix and I feel like there's definitely ways to improve this, but this might be "good enough" for now to run the `/memory` command successfully again.

I am pretty new to the python game so please feel free to adjust this PR as needed.

Happy to learn more about LLamaIndex if you guys have any recommended resources for me to check out that would be awesome!

2023-11-01 16:54 UTC, sarahwooders requested changes
This is a great catch, thanks! 

It might be cleaner to mimic what's being done here https://github.com/cpacker/MemGPT/blob/main/memgpt/memory.py#L223, and return a string (rather than print) for both the empty/non-empty index cases. I think the empty string return was a temporary hack that I forgot to fix because I wasn't sure how to convert the VectorIndex into a nice string representation.

2023-11-01 18:14 UTC, goetzrobin commented
Agreed, @sarahwooders! That solution is much cleaner. 

I saw your work on this: https://github.com/cpacker/MemGPT/pull/226. 

Happy to open a PR to that branch instead. 

Let me know what you think!

2023-11-01 19:57 UTC, sarahwooders commented
Thanks! #226 is still a work in progress and we need this fix ASAP, so it would be better to merge this with main.

2023-11-02 00:17 UTC, goetzrobin commented
@sarahwooders pushed a new version based on your suggestion. let me know if this looks good! Thank you!

2023-11-02 01:44 UTC, sarahwooders approved these changes
Lgtm! Congrats on your first contribution :)

2023-11-02 01:45 UTC, merged