Lancedb
cpacker/MemGPT pull request #455
Opened 2023-11-15 17:33 UTC by PrashantDixit0

**Please describe the purpose of this pull request.**
This is an integration with LanceDB

**How to test**
I have written `tests/test_local_archival.py` and `tests/test_storage.py` and they can be tested in the same way as `Postgres`

2023-11-15 23:04 UTC, sarahwooders requested changes
Could you please add documentation in this page https://memgpt.readthedocs.io/en/latest/storage/ (I think `docs/storage.md`) for LanceDB that includes installation/setup instructions for LanceDB (similar to the Postgres section)? 

The code overall looks good (thanks for the contribution!) -- I'll try to run some testing sometime tomorrow.

2023-11-15 23:04 UTC, sarahwooders commented on pyproject.toml
> +lancedb = "^0.3.3"
Could you please add this an an option dependency, and make an extra called lancedb? e.g. you you can do `pip install pymemgpt[lancedb]` -- we are trying to keep the dependencies are minimal as possible

2023-11-15 23:07 UTC, sarahwooders commented
Also one more note - I saw you updated the `pyproject.toml`, but if you could also update the dependencies through poetry (so the poetry.lock) is updated that would be great.

`pip install poetry`
`poetry add lancedb` 

You can also fix the formatting with `poetry run black . -l 140`

2023-11-16 17:14 UTC, PrashantDixit0 commented
Yes Sure, I'll do that

2023-11-16 18:55 UTC, PrashantDixit0 commented
Done @sarahwooders added docs and dependencies with updated poetry.lock

2023-11-17 18:37 UTC, sarahwooders requested changes
This looks great, thanks for making these changes! I added two more minor comments, but once those changes are made we can merge this in.

2023-11-17 18:37 UTC, sarahwooders commented on pyproject.toml
> +lancedb = "^0.3.3"
Could you please change this to `lancedb = {version = "^0.3.3", optional = true}`?

2023-11-17 18:37 UTC, sarahwooders commented on memgpt/autogen/examples/memgpt_coder_autogen.ipynb
> +    "\n",
Please remove this diff

2023-11-17 18:40 UTC, PrashantDixit0 commented on memgpt/autogen/examples/memgpt_coder_autogen.ipynb
> +    "\n",
Ok, I'll make these changes asap

2023-11-17 19:30 UTC, sarahwooders commented
Could you also fix the formatting on the changed files with `poetry run black . -l 140`? If you give me access to your branch I can also run it for you.

2023-11-17 19:35 UTC, sarahwooders approved these changes
lgtm - thanks for the awesome contribution!

2023-11-17 19:36 UTC, merged

2023-11-17 19:42 UTC, PrashantDixit0 commented
Thank you @sarahwooders for merging lancedb vectordb