LanceDB integration bug fixes and improvements
cpacker/MemGPT pull request #528
Opened 2023-11-29 04:44 UTC by AyushExel

**Please describe the purpose of this pull request.**
Big fix

**How to test**
In the main branch, when you attach a data source to lancedb, the size will always be empty. This branch fixes that
<img width="924" alt="Screenshot 2023-11-29 at 10 12 30 AM" src="https://github.com/cpacker/MemGPT/assets/15766192/133e42b6-3851-4acf-89b6-9a4d4129120c">

**Have you tested this PR?**
For the same data source, now the data is ingested
<img width="1311" alt="Screenshot 2023-11-29 at 10 13 45 AM" src="https://github.com/cpacker/MemGPT/assets/15766192/0101872b-0b9f-43dc-8c65-3adce7058855">

**Related issues or PRs**
[Please link any related GitHub [issues](https://github.com/cpacker/MemGPT/issues) or [PRs](https://github.com/cpacker/MemGPT/pulls).](https://github.com/cpacker/MemGPT/issues/456)

**Is your PR over 500 lines of code?**
No

2023-11-29 04:46 UTC, AyushExel commented on memgpt/connectors/db.py
>          # Assuming query_vec is of same length as embeddings inside table
@cpacker @sarahwooders This part is a little confusing to me -- the `query()` function never gets called for local storage and lancedb.
I tried to just set a breakpoint for both and run some examples after attaching the data source and it never got called.. I'm not sure if I'm doing something wrong.
To repro
```
/attach
ask a question
```

2023-11-29 05:33 UTC, PrashantDixit0 commented
This PR will resolve all the previous issues which came up #456

2023-11-29 07:17 UTC, cpacker requested changes
@AyushExel would you mind running black on the code so that it passes the integration test?

https://github.com/cpacker/MemGPT/blob/main/CONTRIBUTING.md#check-formatting

If you add me as a collaborator to your fork happy to do it for you too.

2023-11-29 08:39 UTC, AyushExel commented
@cpacker done :)

2023-11-30 18:32 UTC, cpacker approved these changes

2023-11-30 18:32 UTC, merged